name       : ruby-erubis
version    : 2.7.0
release    : 2
source     :
    - https://rubygems.org/downloads/erubis-2.7.0.gem : 63653f5174a7997f6f1d6f465fbe1494dcc4bdab1fb8e635f6216989fb1148ba
license    : MIT
component  : programming.ruby
summary    : RubyGem - erubis
description: |
    Erubis is an implementation of eRuby and has the following features:
    * Very fast, almost three times faster than ERB and about 10% faster than eruby.
    * Multi-language support (Ruby/PHP/C/Java/Scheme/Perl/Javascript)
    * Auto escaping support
    * Auto trimming spaces around ''
    * Embedded pattern changeable (default '')
    * Enable to handle Processing Instructions (PI) as embedded pattern (ex. '')
    * Context object available and easy to combine eRuby template with YAML datafile
    * Print statement available
    * Easy to extend and customize in subclass
    * Ruby on Rails support
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install
