name       : ruby-erubis
version    : 2.7.0
release    : 4
source     :
    - https://rubygems.org/downloads/erubis-2.7.0.gem : 63653f5174a7997f6f1d6f465fbe1494dcc4bdab1fb8e635f6216989fb1148ba
license    : MIT
component  : programming.ruby
summary    : Erubis is an implementation of eRuby.
description: |
    Erubis is an implementation of eRuby.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
